spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pet-love

server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
  port: 8081

web:
  cors: allowed-origins=http\://localhost\:4200,https\://localhost:3000,https\://localhost:4000
